domain = "https://www.dotabuff.com/"

[userAgents]
user_agents = [
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.59",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1",
]

[heroes]
hero_names = [
    "abaddon",
    "alchemist",
    "ancient-apparition",
    "anti-mage",
    "arc-warden",
    "axe",
    "bane",
    "batrider",
    "beastmaster",
    "bloodseeker",
    "bounty-hunter",
    "brewmaster",
    "bristleback",
    "broodmother",
    "centaur-warrunner",
    "chaos-knight",
    "chen",
    "clinkz",
    "clockwerk",
    "crystal-maiden",
    "dark-seer",
    "dark-willow",
    "dawnbreaker",
    "dazzle",
    "death-prophet",
    "disruptor",
    "doom",
    "dragon-knight",
    "drow-ranger",
    "earth-spirit",
    "earthshaker",
    "elder-titan",
    "ember-spirit",
    "enchantress",
    "enigma",
    "faceless-void",
    "grimstroke",
    "gyrocopter",
    "hoodwink",
    "huskar",
    "invoker",
    "io",
    "jakiro",
    "juggernaut",
    "keeper-of-the-light",
    "kunkka",
    "legion-commander",
    "leshrac",
    "lich",
    "lifestealer",
    "lina",
    "lion",
    "lone-druid",
    "luna",
    "lycan",
    "magnus",
    "marci",
    "mars",
    "medusa",
    "meepo",
    "mirana",
    "monkey-king",
    "morphling",
    "muerta",
    "naga-siren",
    "natures-prophet",
    "necrophos",
    "night-stalker",
    "nyx-assassin",
    "ogre-magi",
    "omniknight",
    "oracle",
    "outworld-destroyer",
    "pangolier",
    "phantom-assassin",
    "phantom-lancer",
    "phoenix",
    "primal-beast",
    "puck",
    "pudge",
    "pugna",
    "queen-of-pain",
    "razor",
    "riki",
    "rubick",
    "sand-king",
    "shadow-demon",
    "shadow-fiend",
    "shadow-shaman",
    "silencer",
    "skywrath-mage",
    "slardar",
    "slark",
    "snapfire",
    "sniper",
    "spectre",
    "spirit-breaker",
    "storm-spirit",
    "sven",
    "techies",
    "templar-assassin",
    "terrorblade",
    "tidehunter",
    "timbersaw",
    "tinker",
    "tiny",
    "treant-protector",
    "troll-warlord",
    "tusk",
    "underlord",
    "undying",
    "ursa",
    "vengeful-spirit",
    "venomancer",
    "viper",
    "visage",
    "void-spirit",
    "warlock",
    "weaver",
    "windranger",
    "winter-wyvern",
    "witch-doctor",
    "wraith-king",
    "zeus",
]
